### ISSUE TITLE
Cannot query StrictDateTimeField with MongoMock

### ISSUE THREAD

**Issue by defrank** [Scille/umongo#118] opened 2017-09-09 01:02 UTC
StrictDateTimeField ensures timezone awareness by adding `tzinfo` to datetime objects.
MongoMock seems to lose the `tzinfo` in storing the documents.  Querying by timezone-aware datetime objects finds nothing.

```python
from datetime import datetime

from mongomock import MongoClient
from pytz import utc
from umongo import Instance, Document
from umongo.fields import StrictDateTimeField


client = MongoClient(tz_aware=True)
db = client.test
instance = Instance(db)


@instance.register
class Something(Document):

    date = StrictDateTimeField()


if __name__ == '__main__':
    now = datetime.now(utc)
    something = Something(date=now)
    something.commit()

    print(f'query by pk={something.pk}:', Something.find_one({'_id': something.pk}))
    same_something = Something.find_one({'date': now})
    print(f'query by date={now}:', same_something)
    assert same_something is not None
```

```
query by date=2017-09-09 00:48:23.808096+00:00: None
query by pk=59b33a575ee02c03b2b037d6: <object Document __main__.Something({'date': datetime.datetime(2017, 9, 9, 0, 48, 23, 808096), 'id': ObjectId('59b33a575ee02c03b2b037d6')})>
```

MongoMock without umongo works:
```python
from datetime import datetime
from pytz import utc

from mongomock import MongoClient


client = MongoClient()
db = client.test


if __name__ == '__main__':
    now = datetime.now(utc)
    pk = db.something.insert_one({'date': now}).inserted_id
    print(f'query by date={now}:', db.something.find_one({'date': now}))
    print(f'query by pk={pk}:', db.something.find_one({'_id': pk}))
```

```
query by date=2017-09-09 00:59:22.487214+00:00: {'date': datetime.datetime(2017, 9, 9, 0, 59, 22, 487214, tzinfo=<UTC>), '_id': ObjectId('59b33cea5ee02c0e18aec871')}
query by pk=59b33cea5ee02c0e18aec871: {'date': datetime.datetime(2017, 9, 9, 0, 59, 22, 487214, tzinfo=<UTC>), '_id': ObjectId('59b33cea5ee02c0e18aec871')}
```

**Comment by touilleMan** [comment] 2017-09-16 21:13
Sorry, can't reproduce this (at least with my mongomock branch desesperatly waiting to be merged...) :'-(

Here is what I got :
```python
$ python test.py
query by date=2017-09-16 21:11:55.417315+00:00: <object Document __main__.Something({'id': ObjectId('59bd939b79bb12403ba84320'), 'date': datetime.datetime(2017, 9, 16, 21, 11, 55, 417315)})>
query by pk=59bd939b79bb12403ba84320: <object Document __main__.Something({'id': ObjectId('59bd939b79bb12403ba84320'), 'date': datetime.datetime(2017, 9, 16, 21, 11, 55, 417315)})>
```

> StrictDateTimeField ensures timezone awareness by adding tzinfo to datetime objects.

It's not really that : you have to set the `load_as_tz_aware` parameter (default to `False`) to specify if you want your date to be returned as tz-naive (converting the date to utc if it was provided with a timezone) or tz-aware (considering the provided date is UTC if it has no timezone)

The important thing to know is mongodb store all date as UTC timezone naive. So you cannot keep the timezone information with [a regular mongodb ISODate](https://docs.mongodb.com/manual/reference/method/Date/)

**Comment by defrank** [comment] 2017-09-18 14:05
I confirm, this is fixed by your branch, @touilleMan.

**Closed** 2017-09-18 15:02 UTC
